_BASE_: "./bagtricks_R50_IBN_HOSCA_GeM.yml"

MODEL:
  BACKBONE:
    LAST_STRIDE: 1
  HOSCA:
    PART_COMPETITIVE: True
    PART_NUM: 4
    PART_DIM: 256
    PART_MASK_TEMPERATURE: 1.0
    PART_VERTICAL_PRIOR_STRENGTH: 1.0
    PART_VERTICAL_PRIOR_SIGMA: 0.18
    PART_CE_SCALE: 0.5
    PART_TRI_SCALE: 0.5
    PART_BALANCE_SCALE: 0.01
    PART_EVAL_WEIGHT: 0.75
    PART_GRADIENT_ISOLATION: False
    PART_INIT_SEED: 0

OUTPUT_DIR: "logs/Market1501/bagtricks_R50_IBN_HOSCA_PCL"
