"""Paste this block after ``_C.MODEL.HOSCA = CN()`` in FastReID defaults."""

_C.MODEL.HOSCA.PART_COMPETITIVE = False
_C.MODEL.HOSCA.PART_NUM = 4
_C.MODEL.HOSCA.PART_DIM = 256
_C.MODEL.HOSCA.PART_MASK_TEMPERATURE = 1.0
_C.MODEL.HOSCA.PART_VERTICAL_PRIOR_STRENGTH = 1.0
_C.MODEL.HOSCA.PART_VERTICAL_PRIOR_SIGMA = 0.18
_C.MODEL.HOSCA.PART_CE_SCALE = 0.5
_C.MODEL.HOSCA.PART_TRI_SCALE = 0.5
_C.MODEL.HOSCA.PART_BALANCE_SCALE = 0.01
_C.MODEL.HOSCA.PART_EVAL_WEIGHT = 0.75
_C.MODEL.HOSCA.PART_GRADIENT_ISOLATION = False
_C.MODEL.HOSCA.PART_INIT_SEED = 0
